# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentPulse < Formula
  desc "A local event gateway for AI code agents"
  homepage "https://github.com/SantiagoBobrik/agent-pulse"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.3.0/agent-pulse_darwin_amd64.tar.gz"
      sha256 "1a51e1c6787d3ab3a04ae1d39974ec3a2b6edb1b9f21bd4f483e3f31549a1d24"

      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.3.0/agent-pulse_darwin_arm64.tar.gz"
      sha256 "36854e52754869d0ade3e73ebbe6d3c16ef79ab4a4312eff6bf6a2af85f10b3f"

      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.3.0/agent-pulse_linux_amd64.tar.gz"
      sha256 "cfa7c6a538cd25354ce0726a0094cb7e36715ffdc28ca0dea5074e88899a05f0"
      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.3.0/agent-pulse_linux_arm64.tar.gz"
      sha256 "f6b21d41c0be02a7b95145600cee85c045ea5c686f693a2f0522a991596c8a0c"
      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
  end
end
