# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentPulse < Formula
  desc "A local event gateway for AI code agents"
  homepage "https://github.com/SantiagoBobrik/agent-pulse"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.1.0/agent-pulse_darwin_amd64.tar.gz"
      sha256 "3b0b81bac15257f105d2c65aac374a7b27b80c21c7114fe2174c4239579e5d59"

      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.1.0/agent-pulse_darwin_arm64.tar.gz"
      sha256 "51800e706d0c8f0c2c0d5a1a0e1f94320cbf8b37c05e9f6b35e709f733e0291f"

      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.1.0/agent-pulse_linux_amd64.tar.gz"
      sha256 "9bd710764641cf16d8d4bef840ff74ac71e09f732a6d8e12a45c6f0e4c42c96d"
      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.1.0/agent-pulse_linux_arm64.tar.gz"
      sha256 "084806fc27cab61c24b49c54d8d04ae40414421a6388dd43860e8057af6dbd8d"
      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
  end
end
