# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentPulse < Formula
  desc "A local event gateway for AI code agents"
  homepage "https://github.com/SantiagoBobrik/agent-pulse"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.1.1/agent-pulse_darwin_amd64.tar.gz"
      sha256 "819a0dab74b4fefe36ee277ab3a25a7082e8102ec3378026ff04290f5058fa9d"

      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.1.1/agent-pulse_darwin_arm64.tar.gz"
      sha256 "3e965bdce0e1f0950fd5cda969745d0a45c27521b07d5334bace00897103ff33"

      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.1.1/agent-pulse_linux_amd64.tar.gz"
      sha256 "5907f91ff4c018de3805cf61acad2b59ba0e455899fe212e82d39c56b920375e"
      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SantiagoBobrik/agent-pulse/releases/download/v0.1.1/agent-pulse_linux_arm64.tar.gz"
      sha256 "dd9d6eb509cd41215d8717bde72503def2577ccab1d490554f2c7d5da0d31d95"
      define_method(:install) do
        bin.install "agent-pulse"
      end
    end
  end
end
